; Player models configuration file (default).
; File location: $moddir/addons/amx/config/player_models.ini
; To use with "Change Models" plugin.

; Usage format:
; <SteamID|IP> <Terro model> <CT model> <VIP model>
; or
; <admin flags> <Terro model> <CT model> <VIP model>

; Usage examples:
; "STEAM_0:1255113" benladen smith bush
; "STEAM_0:582742" "" "" lara_croft
; "212.52.86.124" "" captain_america "" (only on a NoSteam server [more infos below])
; "cdei" "" chicken predator

; Note: Please make sure your models have been put in the "models/player" folder.
; You can use IP address instead of SteamID, but ONLY if the user in-game
; have a "STEAM_ID_LAN" (local server or CS 1.6/CZ server with dproto module using)
; or on a CS 1.5 Won server.

; Add your player models below.

